### ISSUE TITLE
Make E5 Encoders an optional dependency.

### ISSUE THREAD

**Issue by x-tabdeveloping** [x-tabdeveloping/topic-benchmark#4]
I'm not 100% sure if we should do this, but I have come across multiple occasions where my local installation of turftopic didn't have E5Encoder yet, while I was just trying to export a table. Do we wanna do sth about this @jankounchained ?

**Comment by jankounchained** [comment]
right, it's because i'm installing turftopic from github right now, waiting for the package to be updated on pypi.
we're gonna do that soon, no?
so i wouldn't fix this

**Comment by x-tabdeveloping** [comment]
I did!
